name: Build and deploy ASP.Net Core app to Azure Web App - EduBotSA

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build YourProject/YourProject.sln --configuration Release

      - name: dotnet publish
        run: dotnet publish YourProject/YourProject.sln -c Release -o "${{github.workspace}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{github.workspace}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5D4C899826FC4354B13F7EB3359EF19C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4D63ACF34B884BC2963A9BC2FEC65A08 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2EE56E308CF444A4823C4414A7D0B938 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'EduBotSA'
          slot-name: 'Production'
          package: ${{github.workspace}}/.net-app
